server:
  port: 8080

spring:
  application:
    name: AwsExchange

  datasource:
    url: jdbc:mysql://localhost:3306/exchange
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abc111
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: <|>s{b)?Xw.g={41O7AU-Bi"wQa}zrDO

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001
